### ISSUE TITLE
How does one RUN this on Windows 7 machine ?

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools-vue#3]
Detailed Instructions for a n00b please :dango:

**Comment by TuxNuX** [comment]
https://nodejs.org/en/download/
https://nodesource.com/blog/installing-nodejs-tutorial-windows/
https://git-scm.com/download/win
https://blog.countableset.com/2012/06/07/adding-git-to-windows-7-path/
